from pydantic_settings import BaseSettings
from typing import List
import secrets


class Settings(BaseSettings):
    # Database
    DATABASE_URL: str

    # JWT
    SECRET_KEY: str = secrets.token_urlsafe(32)
    JWT_ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 60
    REFRESH_TOKEN_EXPIRE_DAYS: int = 30

    # Google OAuth
    GOOGLE_CLIENT_ID: str
    GOOGLE_CLIENT_SECRET: str
    GOOGLE_REDIRECT_URI: str = "http://localhost:8000/auth/google/callback"
    GOOGLE_CALENDAR_REDIRECT_URI: str = "http://localhost:8000/onboarding/google-calendar/callback"

    # Stripe
    STRIPE_SECRET_KEY: str
    STRIPE_CLIENT_ID: str          # ca_... from dashboard.stripe.com/settings/connect
    STRIPE_WEBHOOK_SECRET: str
    STRIPE_CONNECT_REDIRECT_URI: str = "http://localhost:8000/onboarding/stripe/callback"
    FRONTEND_URL: str = "http://localhost:3000"

    # Email
    RESEND_API_KEY: str
    EMAIL_FROM: str = "noreply@therapybilling.app"
    EMAIL_FROM_NAME: str = "TherapyBilling"

    # Encryption
    ENCRYPTION_KEY: str  # Fernet key for encrypting OAuth tokens at rest

    # Redis
    REDIS_URL: str = "redis://localhost:6379/0"

    # PDF output directory (receipts generated by US service)
    PDF_OUTPUT_DIR: str = "/tmp/receipts"

    # App
    APP_ENV: str = "development"
    CORS_ORIGINS: str = "http://localhost:3000"

    @property
    def cors_origins_list(self) -> List[str]:
        return [o.strip() for o in self.CORS_ORIGINS.split(",")]

    class Config:
        env_file = ".env"
        case_sensitive = True


settings = Settings()
